"""PACE speed selection: the pure decision layer.

Given a chunk of absolute actions, decide (a) which steps to keep and (b) how fast
to execute each of them. Nothing here touches a policy, an environment, or a robot
-- it is deterministic tensor math, which is what makes it testable offline and
shareable between the simulator and the real arm.

The two speed channels answer different questions:

  * ``speed_from_angle``            -- is the *path* bending? (position deltas)
  * ``speed_from_orientation``      -- is the wrist *rotating* fast? (delta magnitude)
  * ``speed_from_orientation_angle``-- is the rotation *axis* pivoting? (delta bending)

Each maps "how sharp" to a speed in ``[min_speed, max_speed]``; the enabled ones are
combined with ``min`` so any one of them can veto. Lookahead lets a step brake for a
corner that is still a few steps away, which is the difference between slowing down
*into* a turn and slowing down *after* overshooting it.

This is a port of the logic that lived inside ``XVLAPolicy.select_action`` in the
lerobot_uncertainty fork. It is numerically identical to it -- see
``tests/test_pace_parity.py``, which checks against vectors generated by running the
fork's own code.
"""

from __future__ import annotations

import math
from dataclasses import asdict, dataclass, fields

import torch
import torch.nn.functional as F  # noqa: N812

# Absolute actions are laid out [x, y, z, ax, ay, az, gripper, ...]: position in
# dims 0:3 and an axis-angle rotation in dims 3:6.
POS = slice(0, 3)
ORI = slice(3, 6)

_DEG = 180.0 / math.pi
# Both bending channels saturate at a right angle: a 90-degree turn gets min_speed.
_RIGHT_ANGLE = 90.0


@dataclass(frozen=True)
class PaceConfig:
    """Knobs for one PACE run.

    Defaults deliberately mirror the fork's ``_speed_configs.get(...)`` fallbacks, so
    an omitted key behaves the same here as it did there. The defaults are the
    *inert* ones: with no overrides, every step runs at speed 1.0 and nothing is
    skipped.
    """

    max_speed: float = 1.0
    # Speed floor. Callers conventionally set this to max_speed / 2; that convention
    # lives in the experiment config, not here, so this default stays neutral.
    min_speed: float = 1.0
    # Rotation rate (deg/step) tolerated before the orientation channel brakes.
    clamp_deg: float = 5.0

    # Deliver every Nth action instead of every one -- the "skip" baseline.
    action_stride: int = 1
    # Skip only where the path is straight; keep full resolution through corners.
    adaptive_stride: bool = False

    n_lookahead: int = 0
    lookahead_agg: str = "min"  # min | mean | cumulative_bending
    lookahead_target: str = "all"  # all | angle | ori | ori_axis

    enable_angle: bool = True
    enable_ori: bool = True
    enable_ori_axis: bool = True

    # Bang-bang override: snap each step to max or min on a per-step angle threshold.
    speed_quantize: bool = False
    quantize_angle_thr: float = 22.5

    @classmethod
    def from_dict(cls, raw: dict) -> PaceConfig:
        """Build from a loose kwargs dict, ignoring keys that belong to other layers.

        Eval configs carry actuation and environment keys (``speed_up``, ``task_ids``,
        ...) in the same dict; those are not PACE's business and are dropped.
        """
        known = {f.name for f in fields(cls)}
        return cls(**{k: v for k, v in raw.items() if k in known})

    def to_dict(self) -> dict:
        return asdict(self)


def unnormalize_actions(actions: torch.Tensor, stats: dict | None) -> torch.Tensor:
    """Map normalized policy output into absolute action space.

    PACE reasons about geometry -- angles between position deltas, degrees of
    rotation -- so it needs real units, not z-scores. When PACE runs as a pipeline
    step placed after the policy's own unnormalization, ``stats`` is None and this is
    a no-op; the argument exists for the case where PACE sits upstream of it (as it
    did inside the fork's policy).
    """
    if not stats or "action" not in stats:
        return actions.clone()
    s = stats["action"]
    out = actions.clone()
    if "std" in s:
        std = s["std"].to(actions.device)
        mean = s.get("mean", torch.zeros_like(std)).to(actions.device)
        return out * std + mean
    if "max" in s and "min" in s:
        hi, lo = s["max"].to(actions.device), s["min"].to(actions.device)
        return (out + 1) / 2 * (hi - lo) + lo
    return out


def _bend_angles(deltas: torch.Tensor) -> torch.Tensor:
    """Angle in degrees between each consecutive pair of delta vectors.

    Two differencings shorten the sequence by 2, so the last value is replicated
    twice to restore length T. Chunks are regenerated well before their tail is
    consumed, so this extrapolation is not load-bearing.
    """
    a, b = deltas[:, :-1], deltas[:, 1:]
    cos = F.cosine_similarity(a, b, dim=-1, eps=1e-8)
    cos = torch.cat([cos, cos[:, -1:], cos[:, -1:]], dim=-1)
    return torch.acos(torch.clamp(cos, -1.0, 1.0)) * _DEG


def per_step_angle(trajectory: torch.Tensor) -> torch.Tensor:
    """How sharply the *path* turns at each step, in degrees. Shape (B, T)."""
    return _bend_angles(trajectory[:, 1:, POS] - trajectory[:, :-1, POS])


def per_step_orientation_angle(trajectory: torch.Tensor) -> torch.Tensor:
    """How sharply the *rotation axis* pivots at each step, in degrees. Shape (B, T).

    Constant-rate rotation about a fixed axis gives ~0; a 90-degree axis flip gives 90.
    """
    return _bend_angles(trajectory[:, 1:, ORI] - trajectory[:, :-1, ORI])


def _speed_from_bend(angles: torch.Tensor, max_speed: float, min_speed: float) -> torch.Tensor:
    """Linear ramp: straight (0 deg) -> max_speed, right angle or sharper -> min_speed."""
    factors = torch.clamp(_RIGHT_ANGLE - angles, min=0.0) / _RIGHT_ANGLE
    return min_speed + (max_speed - min_speed) * factors


def speed_from_angle(trajectory, max_speed=1.5, min_speed=1.0) -> torch.Tensor:
    """Speed from path curvature."""
    return _speed_from_bend(per_step_angle(trajectory), max_speed, min_speed)


def speed_from_orientation_angle(trajectory, max_speed=1.5, min_speed=1.0) -> torch.Tensor:
    """Speed from rotation-axis curvature.

    Independent of :func:`speed_from_orientation`, which clamps on rotation
    *magnitude*. Combining both keeps two safeties: do not rotate too fast, and do
    not pivot the axis abruptly.
    """
    return _speed_from_bend(per_step_orientation_angle(trajectory), max_speed, min_speed)


def speed_from_orientation(trajectory, max_speed=1.5, min_speed=1.0, clamp_deg=5.0) -> torch.Tensor:
    """Speed from how many degrees the wrist rotates per step.

    Below ``clamp_deg`` costs nothing; from there the speed ramps down linearly and
    hits ``min_speed`` at ``2 * clamp_deg``. ``clamp_deg <= 0`` disables the channel
    (returns ``max_speed`` everywhere) rather than dividing by zero.
    """
    ori_deltas = trajectory[:, 1:, ORI] - trajectory[:, :-1, ORI]
    ori_deltas = torch.cat([ori_deltas, ori_deltas[:, -1:]], dim=1)
    rot_degs = torch.linalg.norm(ori_deltas, dim=-1) * _DEG

    if clamp_deg is None or clamp_deg <= 0:
        return torch.full_like(rot_degs, max_speed)

    excess = torch.clamp(rot_degs - clamp_deg, min=0.0)
    factors = torch.clamp((clamp_deg - excess) / clamp_deg, min=0.0, max=1.0)
    return min_speed + (max_speed - min_speed) * factors


def apply_lookahead(values: torch.Tensor, n: int, agg: str) -> torch.Tensor:
    """Aggregate each step with the ``n`` steps that follow it. Shape (B, T) in and out.

    The tail is padded by replicating the last column, so the end of a chunk is not
    artificially dragged down by futures that do not exist yet.
    """
    if n <= 0:
        return values
    window = [values]
    for k in range(1, n + 1):
        shifted = values.roll(-k, dims=1)
        shifted[:, -k:] = values[:, -1:]
        window.append(shifted)
    stacked = torch.stack(window, dim=0)  # (n+1, B, T)
    if agg == "min":
        return stacked.min(dim=0).values
    if agg == "mean":
        return stacked.mean(dim=0)
    if agg == "sum":
        return stacked.sum(dim=0)
    raise ValueError(f"Unknown lookahead aggregator: {agg}")


def stride_indices(abs_actions: torch.Tensor, cfg: PaceConfig) -> list[int]:
    """Which steps of the chunk to actually execute.

    Plain striding takes every Nth step regardless of what the path is doing.
    ``adaptive_stride`` keeps that rhythm on straight segments but restores every
    step wherever the path bends past ``quantize_angle_thr`` -- skipping through a
    corner is what turns a skip baseline into a missed grasp. The decision is made
    on the full-resolution chunk, before anything is dropped.
    """
    n_steps = abs_actions.shape[1]
    if cfg.action_stride <= 1:
        return list(range(n_steps))
    if not cfg.adaptive_stride:
        return list(range(0, n_steps, cfg.action_stride))
    angles = per_step_angle(abs_actions)[0]
    return [
        i
        for i in range(n_steps)
        if (i % cfg.action_stride == 0) or (float(angles[i]) >= cfg.quantize_angle_thr)
    ]


def compute_speeds(abs_actions: torch.Tensor, cfg: PaceConfig) -> torch.Tensor:
    """Per-step speed multipliers for an (already strided) chunk. Shape (B, T).

    ``abs_actions`` must be in absolute units. Channels that are disabled contribute
    nothing; if all three are off the result is a constant ``max_speed``, which is
    how the "vanilla constant speedup" baseline is expressed.
    """
    ms, mn = cfg.max_speed, cfg.min_speed

    coord = speed_from_angle(abs_actions, ms, mn) if cfg.enable_angle else None
    ori = speed_from_orientation(abs_actions, ms, mn, cfg.clamp_deg) if cfg.enable_ori else None
    ori_axis = speed_from_orientation_angle(abs_actions, ms, mn) if cfg.enable_ori_axis else None

    n = int(cfg.n_lookahead or 0)
    if n > 0:
        agg = cfg.lookahead_agg or "min"
        target = cfg.lookahead_target or "all"

        def wanted(channel: str) -> bool:
            return target in ("all", channel)

        if agg in ("min", "mean"):
            if coord is not None and wanted("angle"):
                coord = apply_lookahead(coord, n, agg)
            if ori is not None and wanted("ori"):
                ori = apply_lookahead(ori, n, agg)
            if ori_axis is not None and wanted("ori_axis"):
                ori_axis = apply_lookahead(ori_axis, n, agg)
        elif agg == "cumulative_bending":
            # Instead of aggregating speeds, sum the raw bend over the window and
            # scale against the worst case (n+1 consecutive right angles). This
            # brakes for a long gradual arc that no single step would flag.
            denom = _RIGHT_ANGLE * (n + 1)
            if coord is not None and wanted("angle"):
                cum = apply_lookahead(per_step_angle(abs_actions), n, "sum")
                coord = mn + (ms - mn) * (torch.clamp(denom - cum, min=0.0) / denom)
            if ori_axis is not None and wanted("ori_axis"):
                cum = apply_lookahead(per_step_orientation_angle(abs_actions), n, "sum")
                ori_axis = mn + (ms - mn) * (torch.clamp(denom - cum, min=0.0) / denom)
            # Rotation *magnitude* has no per-step "bending" reading, so the ori
            # channel stays raw here even when lookahead_target says "ori".
        else:
            raise ValueError(f"Unknown lookahead_agg: {agg}")

    enabled = [s for s in (coord, ori, ori_axis) if s is not None]
    if not enabled:
        return torch.full_like(abs_actions[..., 0], float(ms))

    speeds = enabled[0]
    for s in enabled[1:]:
        speeds = torch.minimum(speeds, s)

    if cfg.speed_quantize:
        # Bang-bang: ignore the ramps entirely and pick a side per step. No
        # lookahead, no accumulation -- deliberately the crudest possible controller,
        # kept as the ablation that shows the ramps are doing work.
        angles = per_step_angle(abs_actions)
        speeds = torch.where(
            angles < cfg.quantize_angle_thr,
            torch.full_like(angles, float(ms)),
            torch.full_like(angles, float(mn)),
        )
    return speeds
